/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ufpb.zoo.views;

import br.com.ufpb.zoo.control.SistemaZoo;
import br.com.ufpb.zoo.model.Animal;
import br.com.ufpb.zoo.run.Projeto;
import br.com.ufpb.zoo.views.tabelas.ModelTableAnimais;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author robson
 * @author Claudio Victor
 */
public class PesquisarAnimaisDoCorredor extends javax.swing.JDialog {

    private static SistemaZoo sisZoo;

    /**
     * Creates new form CadastrarAnimal
     */
    public PesquisarAnimaisDoCorredor(SistemaZoo sistema, java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        this.sisZoo = sistema;
        initComponents();
        preencherCombo();
        URL url = this.getClass().getResource("images/ZooIcone.png");
        Image ZooIcone = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(ZooIcone);
        setIconImage(ZooIcone);
    }

    public void preencherCombo() {
        for (int i = 0; i < sisZoo.getAllHalls().size(); i++) {
            comboCorredor.addItem(sisZoo.getAllHalls().get(i).getNome());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPesquisarAnimalDoCorredor = new javax.swing.JLabel();
        jCorredor = new javax.swing.JLabel();
        comboCorredor = new javax.swing.JComboBox<>();
        btnPesquisarAnimalDoCorredor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAnimaisBloco = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPesquisarAnimalDoCorredor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPesquisarAnimalDoCorredor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPesquisarAnimalDoCorredor.setText("   Pesquisar Animais de um Corredor   ");
        jPesquisarAnimalDoCorredor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jCorredor.setText("Corredor:");

        btnPesquisarAnimalDoCorredor.setText("Pesquisar");
        btnPesquisarAnimalDoCorredor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPesquisarAnimalDoCorredor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarAnimalDoCorredorMouseClicked(evt);
            }
        });
        btnPesquisarAnimalDoCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarAnimalDoCorredorActionPerformed(evt);
            }
        });

        tabelaAnimaisBloco.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaAnimaisBloco);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCorredor)
                        .addGap(18, 18, 18)
                        .addComponent(comboCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisarAnimalDoCorredor)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPesquisarAnimalDoCorredor)
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPesquisarAnimalDoCorredor)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCorredor)
                    .addComponent(btnPesquisarAnimalDoCorredor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarAnimalDoCorredorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarAnimalDoCorredorMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnPesquisarAnimalDoCorredorMouseClicked

    private void btnPesquisarAnimalDoCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarAnimalDoCorredorActionPerformed
        // TODO add your handling code here:
        String corredor = comboCorredor.getSelectedItem().toString();
        ModelTableAnimais ma = new ModelTableAnimais((ArrayList) sisZoo.pesquisaAnimaisDeUmCorredor(corredor));
        tabelaAnimaisBloco.setModel(ma);
    }//GEN-LAST:event_btnPesquisarAnimalDoCorredorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarAnimaisDoCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarAnimaisDoCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarAnimaisDoCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarAnimaisDoCorredor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PesquisarAnimaisDoCorredor dialog = new PesquisarAnimaisDoCorredor(sisZoo, new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisarAnimalDoCorredor;
    private javax.swing.JComboBox<String> comboCorredor;
    private javax.swing.JLabel jCorredor;
    private javax.swing.JLabel jPesquisarAnimalDoCorredor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaAnimaisBloco;
    // End of variables declaration//GEN-END:variables

}
