/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ufpb.zoo.views;

/**
 *
 * @author robson
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem11 = new javax.swing.JMenuItem();
        jImagemZoo = new javax.swing.JLabel();
        jBarraDeMenu = new javax.swing.JMenuBar();
        jCadastro = new javax.swing.JMenu();
        jFuncionario = new javax.swing.JMenuItem();
        jAnimal = new javax.swing.JMenuItem();
        jBlocoSub = new javax.swing.JMenu();
        jCooredorSubBloco = new javax.swing.JMenuItem();
        jJaulaSubBloco = new javax.swing.JMenuItem();
        jResponsavelSubBloco = new javax.swing.JMenuItem();
        fFuncionariosSubBloco = new javax.swing.JMenuItem();
        JPesquisa = new javax.swing.JMenu();
        jPesquisaAnimal = new javax.swing.JMenu();
        jLocal = new javax.swing.JMenuItem();
        jBloco = new javax.swing.JMenuItem();
        jCorredor = new javax.swing.JMenuItem();
        jVisaoGeral = new javax.swing.JMenu();
        jTodosOsFuncionarios = new javax.swing.JMenuItem();
        jTodosOsBlocos = new javax.swing.JMenuItem();
        jTodosOsCorredores = new javax.swing.JMenuItem();
        jTodasAsJaulas = new javax.swing.JMenuItem();
        jTodosOsAnimais = new javax.swing.JMenuItem();

        jMenuItem11.setText("jMenuItem11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jImagemZoo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ufpb/zoo/images/Zoo_1.png"))); // NOI18N
        jImagemZoo.setText("jLabel1");
        jImagemZoo.setMaximumSize(new java.awt.Dimension(800, 500));
        jImagemZoo.setMinimumSize(new java.awt.Dimension(800, 500));

        jCadastro.setText("Cadastro");
        jCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jFuncionario.setText("Funcionário");
        jFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCadastro.add(jFuncionario);

        jAnimal.setText("Animal");
        jAnimal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAnimalActionPerformed(evt);
            }
        });
        jCadastro.add(jAnimal);

        jBlocoSub.setText("Bloco");
        jBlocoSub.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jCooredorSubBloco.setText("Corredor");
        jCooredorSubBloco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jCooredorSubBloco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCooredorSubBlocoActionPerformed(evt);
            }
        });
        jBlocoSub.add(jCooredorSubBloco);

        jJaulaSubBloco.setText("Jaula");
        jJaulaSubBloco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBlocoSub.add(jJaulaSubBloco);

        jResponsavelSubBloco.setText("Responsável");
        jResponsavelSubBloco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBlocoSub.add(jResponsavelSubBloco);

        fFuncionariosSubBloco.setText("Funcionários");
        fFuncionariosSubBloco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBlocoSub.add(fFuncionariosSubBloco);

        jCadastro.add(jBlocoSub);

        jBarraDeMenu.add(jCadastro);
        jCadastro.getAccessibleContext().setAccessibleDescription("");

        JPesquisa.setText("Pesquisa");
        JPesquisa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPesquisaAnimal.setText("Animal");
        jPesquisaAnimal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLocal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jLocal.setText("Local de um animal");
        jLocal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLocalActionPerformed(evt);
            }
        });
        jPesquisaAnimal.add(jLocal);

        jBloco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jBloco.setText("Animais do bloco");
        jBloco.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPesquisaAnimal.add(jBloco);

        jCorredor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jCorredor.setText("Animais do corredor");
        jCorredor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPesquisaAnimal.add(jCorredor);

        JPesquisa.add(jPesquisaAnimal);

        jBarraDeMenu.add(JPesquisa);

        jVisaoGeral.setText("Visão Geral");
        jVisaoGeral.setActionCommand("");
        jVisaoGeral.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTodosOsFuncionarios.setText("Todos os Funcionários");
        jVisaoGeral.add(jTodosOsFuncionarios);

        jTodosOsBlocos.setText("Todos os blocos");
        jTodosOsBlocos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jVisaoGeral.add(jTodosOsBlocos);

        jTodosOsCorredores.setText("Todos os corredores");
        jTodosOsCorredores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jVisaoGeral.add(jTodosOsCorredores);

        jTodasAsJaulas.setText("Todos as jaulas");
        jTodasAsJaulas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTodasAsJaulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTodasAsJaulasActionPerformed(evt);
            }
        });
        jVisaoGeral.add(jTodasAsJaulas);

        jTodosOsAnimais.setText("Todos os animais");
        jTodosOsAnimais.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jVisaoGeral.add(jTodosOsAnimais);

        jBarraDeMenu.add(jVisaoGeral);

        setJMenuBar(jBarraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jImagemZoo, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jImagemZoo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCooredorSubBlocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCooredorSubBlocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCooredorSubBlocoActionPerformed

    private void jLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLocalActionPerformed

    private void jTodasAsJaulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTodasAsJaulasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTodasAsJaulasActionPerformed

    private void jAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAnimalActionPerformed
        // TODO add your handling code here:
        CadastrarAnimal ca = new CadastrarAnimal(this, rootPaneCheckingEnabled);
        ca.setLocationRelativeTo(null);
        ca.setVisible(true);
    }//GEN-LAST:event_jAnimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JPesquisa;
    private javax.swing.JMenuItem fFuncionariosSubBloco;
    private javax.swing.JMenuItem jAnimal;
    private javax.swing.JMenuBar jBarraDeMenu;
    private javax.swing.JMenuItem jBloco;
    private javax.swing.JMenu jBlocoSub;
    private javax.swing.JMenu jCadastro;
    private javax.swing.JMenuItem jCooredorSubBloco;
    private javax.swing.JMenuItem jCorredor;
    private javax.swing.JMenuItem jFuncionario;
    private javax.swing.JLabel jImagemZoo;
    private javax.swing.JMenuItem jJaulaSubBloco;
    private javax.swing.JMenuItem jLocal;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenu jPesquisaAnimal;
    private javax.swing.JMenuItem jResponsavelSubBloco;
    private javax.swing.JMenuItem jTodasAsJaulas;
    private javax.swing.JMenuItem jTodosOsAnimais;
    private javax.swing.JMenuItem jTodosOsBlocos;
    private javax.swing.JMenuItem jTodosOsCorredores;
    private javax.swing.JMenuItem jTodosOsFuncionarios;
    private javax.swing.JMenu jVisaoGeral;
    // End of variables declaration//GEN-END:variables
}
